# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.loopsystems.ca:
    container_name: orderer.loopsystems.ca
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.loopsystems.ca/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.loopsystems.ca/tls/:/var/hyperledger/orderer/tls
    - orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  ca.loopsystems.ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.loopsystems.ca
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/ca.loopsystems.ca/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.loopsystems.ca
    networks:
      - loopNetw

  peer0.loop.loopsystems.ca:
    container_name: peer0.loop.loopsystems.ca
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.loop.loopsystems.ca
      - CORE_PEER_ADDRESS=peer0.loop.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.loop.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.loop.loopsystems.ca:7051
      - CORE_PEER_LOCALMSPID=LoopMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/loop.loopsystems.ca/peers/peer0.loop.loopsystems.ca/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/loop.loopsystems.ca/peers/peer0.loop.loopsystems.ca/tls:/etc/hyperledger/fabric/tls
        - peer0.loop.loopsystems.ca:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.loop.loopsystems.ca:
    container_name: peer1.loop.loopsystems.ca
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.loopsystems.ca
      - CORE_PEER_ADDRESS=peer1.loop.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.loop.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.loop.loopsystems.ca:7051
      - CORE_PEER_LOCALMSPID=LoopMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/loop.loopsystems.ca/peers/peer1.loop.loopsystems.ca/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/loop.loopsystems.ca/peers/peer1.loop.loopsystems.ca/tls:/etc/hyperledger/fabric/tls
        - peer1.loop.loopsystems.ca:/var/hyperledger/production

    ports:
      - 8051:7051
      - 8053:7053

  peer0.sender.loopsystems.ca:
    container_name: peer0.sender.loopsystems.ca
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sender.loopsystems.ca
      - CORE_PEER_ADDRESS=peer0.sender.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sender.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.sender.loopsystems.ca:7051
      - CORE_PEER_LOCALMSPID=SenderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sender.loopsystems.ca/peers/peer0.sender.loopsystems.ca/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sender.loopsystems.ca/peers/peer0.sender.loopsystems.ca/tls:/etc/hyperledger/fabric/tls
        - peer0.sender.loopsystems.ca:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer1.sender.loopsystems.ca:
    container_name: peer1.sender.loopsystems.ca
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.sender.loopsystems.ca
      - CORE_PEER_ADDRESS=peer1.sender.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.sender.loopsystems.ca:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sender.loopsystems.ca:7051
      - CORE_PEER_LOCALMSPID=SenderMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sender.loopsystems.ca/peers/peer1.sender.loopsystems.ca/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sender.loopsystems.ca/peers/peer1.sender.loopsystems.ca/tls:/etc/hyperledger/fabric/tls
        - peer1.sender.loopsystems.ca:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

